[timestep]
fixed = true

[domain]
min = [-1, -1]
max = [1, 1]
adjustParticle = false
adjustDomain = false

[compute]
device='cuda'

[particle]
radius = 0.025

[gravity]
magnitude = 0

[fluid]
c0 = 100

[simulation]
boundaryScheme = 'solid'
verbose = false
densityScheme = 'continuum'
scheme = 'deltaSPH'
mode = 'generative'

[pressure]
fluidPressureTerm = 'TaitEOS'
boundaryPressureTerm = 'PBSPH'
gamma = 7.0

[diffusion]
velocityScheme = 'deltaSPH'
densityScheme = 'MOG'
boundaryDiffusion = 0.01
fluidDiffusion = 0.01
alpha = 0.01
delta = 0.1
kinematic = 0.0

[integration]
scheme = 'RK4'
dt = 0.001

[export]
active = true
prefix = 'generative'
staticBoundary = true
interval = 1

[generative]
nd = 0
nb = 32
border = 3
n = 256
res = 2
octaves = 1
lacunarity = 2
persistance = 0.25
seed = 1337
boundaryWidth = 0.5